# Generated by Django 5.1.2 on 2025-04-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured Agent'),
        ),
    ]
