# Generated by Django 5.1.2 on 2025-04-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='featured_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Featured Until'),
        ),
        migrations.AddField(
            model_name='agent',
            name='is_permanently_featured',
            field=models.BooleanField(default=False, verbose_name='Permanently Featured'),
        ),
    ]
