# Generated by Django 5.1.2 on 2025-04-13 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_featured_until_agent_is_permanently_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='featured',
        ),
    ]
