# Generated by Django 5.1.2 on 2025-04-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_remove_agent_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='featured_until',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='is_permanently_featured',
        ),
        migrations.AddField(
            model_name='agent',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured Agent'),
        ),
    ]
