# Generated by Django 5.1.2 on 2025-04-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_remove_agent_featured_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='bio',
            field=models.TextField(blank=True, help_text='A short biography or personal description', null=True),
        ),
    ]
