# Generated by Django 5.1.2 on 2025-04-14 10:16

import agents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agent_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=agents.models.upload_to),
        ),
    ]
