# Generated by Django 5.1.2 on 2025-05-03 10:14

import agents.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_agentrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.ImageField(upload_to=agents.models.verification_upload_to)),
                ('photo', models.ImageField(upload_to=agents.models.verification_upload_to)),
                ('business_registration', models.FileField(blank=True, help_text='Optional business registration document', null=True, upload_to=agents.models.verification_upload_to)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='agents.agent')),
            ],
        ),
    ]
