# Generated by Django 5.1.2 on 2025-02-25 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0022_marketpropertyfile_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('one_time', 'One Time Payment'), ('3_months', '3 Months Payment'), ('6_months', '6 Months Payment'), ('12_months', '12 Months Payment')], max_length=20, unique=True)),
                ('duration_months', models.PositiveIntegerField(editable=False)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPurchase',
            fields=[
                ('id', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('currency', models.CharField(editable=False, max_length=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('canceled', 'Canceled'), ('confirmed', 'Confirmed'), ('completed', 'Completed Payment')], default='created', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('payment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.paymentplan')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.marketproperty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='purchases.propertypurchase')),
            ],
        ),
    ]
