# Generated by Django 5.1.2 on 2024-12-14 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_question_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
