# Generated by Django 5.1.2 on 2024-12-16 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_userprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='total',
        ),
    ]
