# Generated by Django 5.1.2 on 2024-12-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_userprogress_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
