# Generated by Django 5.1.2 on 2025-01-29 02:24

import course.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_userprogress_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, help_text='Category of the course (e.g., Programming, Design, Business)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.DurationField(blank=True, help_text='Duration of the course', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='enrollment_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of students enrolled in the course'),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=course.models.upload_to),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(blank=True, help_text='Name of the course instructor', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the course currently active?'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Is the course free?'),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(default='English', help_text='Language of the course', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=models.TextField(blank=True, help_text='What students will learn from the course', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', help_text='Difficulty level of the course', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True, help_text='Prerequisites for the course', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price of the course', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.FloatField(blank=True, help_text='Rating should be between 0.0 and 5.0', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
