# Generated by Django 5.1.2 on 2025-01-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_userprogress_date_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Status of the course (Draft or Published)', max_length=10),
        ),
    ]
