# Generated by Django 5.1.2 on 2025-01-30 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_review_user_alter_course_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='rating',
        ),
    ]
