# Generated by Django 5.1.2 on 2025-01-30 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_remove_course_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrollment_count',
        ),
    ]
