# Generated by Django 5.1.2 on 2025-01-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_lesson_image_module_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='grade',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('below_average', 'Below Average'), ('poor', 'Poor')], default='average', max_length=15),
        ),
    ]
