# Generated by Django 5.1.2 on 2025-04-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planduration',
            options={},
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='paystack_plan_code',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='price',
        ),
        migrations.AlterField(
            model_name='planduration',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Naira'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='NGN', max_length=3),
        ),
        migrations.AlterField(
            model_name='planduration',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planduration',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='image',
            field=models.URLField(default='https://images.unsplash.com/photo-1579621970563-ebec7560ff3e...', max_length=500),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=100, unique=True),
        ),
    ]
