# Generated by Django 5.1.2 on 2025-04-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_planduration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='paystack_plan_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
