# Generated by Django 5.1.2 on 2025-04-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptionplan_paystack_plan_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='paystack_plan_code',
        ),
        migrations.AddField(
            model_name='planduration',
            name='paystack_plan_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
