# Generated by Django 5.1.2 on 2025-04-19 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_remove_subscriptionplan_paystack_plan_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='plan_duration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_subscriptions', to='subscriptions.planduration'),
        ),
    ]
