# Generated by Django 5.1.2 on 2025-04-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_alter_usersubscription_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='plan_duration',
        ),
    ]
