# Generated by Django 5.1.2 on 2024-12-25 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NeighborhoodInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkability_score', models.FloatField(blank=True, null=True)),
                ('amenities', models.JSONField(blank=True, null=True)),
                ('crime_rate', models.FloatField(blank=True, null=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trends.location')),
            ],
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('average_sale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('average_rental_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('supply', models.IntegerField()),
                ('demand', models.IntegerField()),
                ('year_over_year_price_change', models.FloatField()),
                ('month_over_month_price_change', models.FloatField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trends.location')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trends.propertytype')),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('predicted_sale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('predicted_rental_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trends.location')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trends.propertytype')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_date', models.DateField(auto_now_add=True)),
                ('forecast', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trends.forecast')),
                ('insights', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trends.neighborhoodinsight')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trends.location')),
                ('market_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trends.marketdata')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trends.propertytype')),
            ],
        ),
    ]
