# Generated by Django 5.1.2 on 2025-02-10 12:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='forecast',
        ),
        migrations.RemoveField(
            model_name='marketdata',
            name='location',
        ),
        migrations.RemoveField(
            model_name='report',
            name='location',
        ),
        migrations.RemoveField(
            model_name='neighborhoodinsight',
            name='location',
        ),
        migrations.RemoveField(
            model_name='marketdata',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='report',
            name='market_data',
        ),
        migrations.RemoveField(
            model_name='report',
            name='insights',
        ),
        migrations.RemoveField(
            model_name='report',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='report',
            name='generated_date',
        ),
        migrations.AddField(
            model_name='report',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='report',
            name='body',
            field=models.TextField(default=1, help_text='Detailed content of the report'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='report',
            name='source',
            field=models.CharField(default=1, help_text='Name of the source of the report', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='summary',
            field=models.TextField(default=1, help_text='A brief overview of the report'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='url',
            field=models.URLField(blank=True, help_text='External link for more details', null=True),
        ),
        migrations.DeleteModel(
            name='Forecast',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='MarketData',
        ),
        migrations.DeleteModel(
            name='NeighborhoodInsight',
        ),
        migrations.DeleteModel(
            name='PropertyType',
        ),
    ]
