# Generated by Django 5.1.2 on 2025-02-10 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0002_remove_report_forecast_remove_marketdata_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='summary',
        ),
    ]
