# Generated by Django 5.1.2 on 2025-02-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0003_remove_report_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this report has been viewed'),
        ),
    ]
