# Generated by Django 5.1.2 on 2025-02-11 11:48

import django.db.models.deletion
import trends.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0004_report_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.ForeignKey(default=trends.models.Category.get_default_category, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='trends.category'),
        ),
    ]
