# Generated by Django 5.1.2 on 2025-05-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0005_category_report_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='publish',
            field=models.BooleanField(default=False, help_text='Whether the report is published or not'),
        ),
    ]
