# Generated by Django 5.1.2 on 2024-11-22 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_payment_status'),
        ('projects', '0007_alter_project_project_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='project_name',
        ),
        migrations.AddField(
            model_name='order',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='projects.project'),
            preserve_default=False,
        ),
    ]
