# Generated by Django 5.1.2 on 2024-11-26 03:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_project_alter_order_user'),
        ('projects', '0008_project_ordered_slots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('user', 'project'), name='unique_user_project_order'),
        ),
    ]
