# Generated by Django 5.1.2 on 2024-11-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_unique_user_project_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('not_paid', 'Not Paid'), ('paid', 'Paid'), ('payment_confirmed', 'Payment Confirmed')], default='not_paid', max_length=20),
        ),
    ]
