# Generated by Django 5.1.2 on 2024-12-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_payment_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_user_project_order',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('not_paid', 'Not Paid'), ('paid', 'Paid'), ('payment_confirm', 'Payment Confirmed')], default='not_paid', max_length=20),
        ),
    ]
