# Generated by Django 5.1.2 on 2024-12-21 22:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(help_text='Name of the savings goal.', max_length=255)),
                ('target_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total savings goal in Naira.', max_digits=15)),
                ('current_savings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount saved so far.', max_digits=15)),
                ('start_date', models.DateField(help_text='The date when savings start.')),
                ('end_date', models.DateField(help_text='The target completion date.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_targets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount of the contribution.', max_digits=15)),
                ('date', models.DateField(help_text='Date of the contribution.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='analyser.financialtarget')),
            ],
        ),
    ]
