# Generated by Django 5.1.2 on 2024-12-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtarget',
            name='achieved_at',
            field=models.DateField(blank=True, help_text='Date when the target was achieved.', null=True),
        ),
    ]
