# Generated by Django 5.1.2 on 2024-12-29 00:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0002_financialtarget_achieved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtarget',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen')], default='NGN', max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='financialtarget',
            name='timeframe',
            field=models.PositiveIntegerField(default=1, help_text='The timeframe for achieving the target in months.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financialtarget',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total savings goal.', max_digits=15),
        ),
    ]
