# Generated by Django 5.1.2 on 2024-12-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0003_financialtarget_currency_financialtarget_timeframe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtarget',
            name='end_date',
            field=models.DateField(blank=True, help_text='The target completion date.', null=True),
        ),
        migrations.AlterField(
            model_name='financialtarget',
            name='start_date',
            field=models.DateField(blank=True, help_text='The date when savings start.', null=True),
        ),
    ]
