# Generated by Django 5.1.2 on 2024-12-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0004_alter_financialtarget_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtarget',
            name='timeframe',
            field=models.PositiveIntegerField(help_text='The timeframe for achieving the target in years.'),
        ),
    ]
