# Generated by Django 5.1.2 on 2024-12-11 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the property listing', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the property')),
                ('property_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condominium'), ('land', 'Land'), ('commercial', 'Commercial')], help_text='Type of property', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the property in USD', max_digits=12)),
                ('address', models.TextField(help_text='Address of the property')),
                ('city', models.CharField(help_text='City where the property is located', max_length=100)),
                ('state', models.CharField(help_text='State where the property is located', max_length=100)),
                ('zip_code', models.CharField(help_text='Zip code of the property location', max_length=20)),
                ('bedrooms', models.PositiveIntegerField(blank=True, help_text='Number of bedrooms', null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, help_text='Number of bathrooms (e.g., 1.5)', max_digits=4, null=True)),
                ('square_feet', models.PositiveIntegerField(blank=True, help_text='Square footage of the property', null=True)),
                ('lot_size', models.DecimalField(blank=True, decimal_places=2, help_text='Lot size in acres', max_digits=10, null=True)),
                ('year_built', models.PositiveIntegerField(blank=True, help_text='Year the property was built', null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('sold', 'Sold')], default='available', help_text='Current status of the listing', max_length=20)),
                ('listed_date', models.DateTimeField(auto_now_add=True, help_text='Date when the property was listed')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Date when the property details were last updated')),
                ('image', models.ImageField(blank=True, help_text='Main image for the property', null=True, upload_to='property_images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MarketProperty',
                'verbose_name_plural': 'MarketProperties',
                'ordering': ['-listed_date'],
            },
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
