# Generated by Django 5.1.2 on 2025-01-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_marketproperty_delete_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketproperty',
            name='square_feet',
            field=models.PositiveIntegerField(blank=True, help_text='Square meter of the property', null=True),
        ),
        migrations.AlterField(
            model_name='marketproperty',
            name='zip_code',
            field=models.CharField(blank=True, help_text='Zip code of the property location', max_length=20, null=True),
        ),
    ]
