# Generated by Django 5.1.2 on 2025-01-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_marketproperty_currency_alter_marketproperty_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketproperty',
            name='availability',
            field=models.CharField(choices=[('now', 'Available Now'), ('date', 'Available from Specified Date')], default='now', max_length=10),
        ),
        migrations.AddField(
            model_name='marketproperty',
            name='availability_date',
            field=models.DateField(blank=True, help_text="Specify date if 'Available from Specified Date' is selected.", null=True),
        ),
        migrations.AddField(
            model_name='marketproperty',
            name='coordinate_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketproperty',
            name='listing_purpose',
            field=models.CharField(choices=[('sale', 'For Sale'), ('lease', 'For Lease'), ('rent', 'For Rent')], default='sale', max_length=10),
        ),
        migrations.AlterField(
            model_name='marketproperty',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('land', 'Land'), ('commercial', 'Commercial Property'), ('office', 'Office Space'), ('warehouse', 'Warehouse'), ('shop', 'Shop/Store'), ('duplex', 'Duplex'), ('bungalow', 'Bungalow'), ('terrace', 'Terrace'), ('semi_detached', 'Semi-Detached House'), ('detached', 'Detached House'), ('farm_land', 'Farm Land'), ('industrial', 'Industrial Property'), ('short_let', 'Short Let'), ('studio', 'Studio Apartment')], help_text='Type of property', max_length=50),
        ),
        migrations.AlterField(
            model_name='marketproperty',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('sold', 'Sold')], default='available', help_text='Current status of the listing', max_length=20),
        ),
    ]
