# Generated by Django 5.1.2 on 2025-01-09 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_marketproperty_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketproperty',
            name='status',
        ),
    ]
