# Generated by Django 5.1.2 on 2025-01-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_remove_marketproperty_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketproperty',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of times the property has been viewed.', null=True),
        ),
        migrations.AlterField(
            model_name='marketproperty',
            name='lot_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Plot size in square meter', max_digits=10, null=True),
        ),
    ]
