# Generated by Django 5.1.2 on 2025-01-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_marketproperty_views_alter_marketproperty_lot_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketproperty',
            name='bookmarked',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of times the property has been bookmarked.', null=True),
        ),
        migrations.AddField(
            model_name='marketproperty',
            name='inquiries',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of times the user has been contacted for the property.', null=True),
        ),
    ]
