# Generated by Django 5.1.2 on 2025-01-18 16:40

import market.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=market.models.upload_to),
        ),
    ]
