# Generated by Django 5.1.2 on 2025-01-22 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_alter_propertyimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negotiable', models.CharField(choices=[('yes', 'Yes'), ('slightly', 'Slightly'), ('no', 'No')], default='no', help_text='Is the property price negotiable?', max_length=10)),
                ('furnished', models.BooleanField(default=False, help_text='Is the property furnished?')),
                ('pet_friendly', models.BooleanField(default=False, help_text='Is the property pet-friendly?')),
                ('parking_available', models.BooleanField(default=False, help_text='Does the property include parking space?')),
                ('swimming_pool', models.BooleanField(default=False, help_text='Does the property have a swimming pool?')),
                ('garden', models.BooleanField(default=False, help_text='Does the property include a garden?')),
                ('electricity_proximity', models.CharField(choices=[('nearby', 'Nearby (Less than 100m)'), ('moderate', 'Moderate (100m - 500m)'), ('far', 'Far (Above 500m)')], default='moderate', help_text='Proximity to electricity connection.', max_length=10)),
                ('road_network', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', help_text='Quality of the road network around the property.', max_length=10)),
                ('development_level', models.CharField(choices=[('high', 'Highly Developed'), ('moderate', 'Moderately Developed'), ('low', 'Sparsely Developed'), ('undeveloped', 'Undeveloped')], default='moderate', help_text='Level of development in the surrounding area.', max_length=15)),
                ('water_supply', models.BooleanField(default=False, help_text='Is there a reliable water supply to the property?')),
                ('security', models.BooleanField(default=False, help_text='Is the area secure?')),
                ('additional_features', models.TextField(blank=True, help_text='Any additional features not listed above.', null=True)),
                ('market_property', models.ForeignKey(help_text='The market property this feature is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='market.marketproperty')),
            ],
        ),
    ]
