# Generated by Django 5.1.2 on 2025-01-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_marketfeatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketfeatures',
            name='verified_user',
            field=models.BooleanField(default=False, help_text='Automatically marked true if the property owner is verified.'),
        ),
    ]
