# Generated by Django 5.1.2 on 2025-01-22 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_marketfeatures_verified_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketfeatures',
            old_name='market_property',
            new_name='property',
        ),
    ]
