# Generated by Django 5.1.2 on 2025-01-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_rename_market_property_marketfeatures_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketfeatures',
            old_name='property',
            new_name='market_property',
        ),
    ]
