# Generated by Django 5.1.2 on 2025-01-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_rename_property_marketfeatures_market_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
