# Generated by Django 5.1.2 on 2025-02-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_propertyimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketfeatures',
            name='electricity_proximity',
            field=models.CharField(choices=[('nearby', 'Nearby (Less than 100m)'), ('moderate', 'Moderate (100m - 500m)'), ('far', 'Far (Above 500m)'), ('available', 'Available')], default='moderate', help_text='Proximity to electricity connection.', max_length=10),
        ),
    ]
