# Generated by Django 5.1.2 on 2025-02-02 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_alter_marketfeatures_electricity_proximity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketCoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_coordinates', to='market.marketproperty')),
            ],
        ),
    ]
