# Generated by Django 5.1.2 on 2025-02-05 08:08

import django.db.models.deletion
import market.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_marketcoordinate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPropertyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=market.models.upload_to)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_property_files', to='market.marketproperty')),
            ],
        ),
    ]
