# Generated by Django 5.1.2 on 2025-02-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_marketpropertyfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketpropertyfile',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
