# Generated by Django 5.1.2 on 2025-02-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0022_marketpropertyfile_image_url'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketproperty',
            name='payment_plans',
            field=models.ManyToManyField(related_name='properties', to='purchases.paymentplan'),
        ),
    ]
