# Generated by Django 5.1.2 on 2025-02-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0023_marketproperty_payment_plans'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketproperty',
            name='payment_plans',
            field=models.ManyToManyField(blank=True, related_name='properties', to='purchases.paymentplan'),
        ),
    ]
