# Generated by Django 5.1.2 on 2024-11-12 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cost_per_slot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_slots', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=255)),
                ('type_of_project', models.CharField(choices=[('SOLAR', 'Solar'), ('WIND', 'Wind'), ('REAL_ESTATE', 'Real Estate'), ('AGRICULTURE', 'Agriculture'), ('TECH', 'Technology')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
        ),
    ]
