# Generated by Django 5.1.2 on 2024-11-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(choices=[('NGN', 'NGN'), ('EUR', 'EUR'), ('USD', 'USD')], default='NGN', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Open', 'Open'), ('Closed', 'Closed')], default='Draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='type_of_project',
            field=models.CharField(choices=[('House', 'House'), ('Land', 'Land')], max_length=20),
        ),
    ]
