# Generated by Django 5.1.2 on 2024-11-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_currency_alter_project_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='num_slots',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
