# Generated by Django 5.1.2 on 2024-11-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_num_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_reference',
            field=models.CharField(blank=True, editable=False, max_length=7, null=True, unique=True),
        ),
    ]
