# Generated by Django 5.1.2 on 2024-11-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_project_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_reference',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
