# Generated by Django 5.1.2 on 2024-11-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_project_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ordered_slots',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
