# Generated by Django 5.1.2 on 2025-01-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_user_phone_number_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='postal_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
