# Generated by Django 5.1.2 on 2025-01-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_postal_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='postal_address',
        ),
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
