# Generated by Django 5.1.2 on 2025-02-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='contact_by_whatsapp',
            field=models.BooleanField(default=False),
        ),
    ]
