# Generated by Django 5.1.2 on 2025-02-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default=1, help_text='State where the property is located', max_length=100),
            preserve_default=False,
        ),
    ]
