# Generated by Django 5.1.2 on 2025-02-26 12:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_user_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_referral_earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
