# Generated by Django 5.1.2 on 2025-03-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_user_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False, verbose_name='Is Agent'),
        ),
    ]
