# Generated by Django 5.1.2 on 2025-04-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_user_is_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='A short biography or personal description', null=True),
        ),
    ]
