# Generated by Django 5.1.2 on 2024-11-22 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0007_alter_project_project_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_return', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='DividendShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('retention_percentage', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('final_share_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_return', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_slots', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dividend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='dividend.dividend')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividend_shares', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
