# Generated by Django 5.1.2 on 2024-11-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividend',
            name='month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
