# Generated by Django 5.1.2 on 2025-04-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
