# Generated by Django 5.1.2 on 2025-04-21 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='title',
            new_name='position',
        ),
    ]
