# Generated by Django 5.1.2 on 2024-11-25 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holding',
            old_name='quantity',
            new_name='slots',
        ),
    ]
