# Generated by Django 5.1.2 on 2024-11-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0002_rename_quantity_holding_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='payment_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
