# Generated by Django 5.1.2 on 2024-12-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_property_address_property_expenses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='photos',
        ),
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='year_bought',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('land', 'Land'), ('private', 'Private House'), ('commercial', 'Commercial Property'), ('residential', 'Residential Property')], max_length=50),
        ),
    ]
