# Generated by Django 5.1.2 on 2024-12-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_property_photos_property_area_property_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='area_sqm',
        ),
        migrations.AlterField(
            model_name='property',
            name='expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='num_units',
            field=models.IntegerField(default=1),
        ),
    ]
