# Generated by Django 5.1.2 on 2024-12-08 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_expenses_description_income_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='expense_type',
        ),
        migrations.RemoveField(
            model_name='income',
            name='income_type',
        ),
    ]
