# Generated by Django 5.1.2 on 2024-12-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_expenses_expense_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AddField(
            model_name='property',
            name='slot_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per slot for group-owned properties.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='total_slots',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of slots for group-owned properties.', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='user_slots',
            field=models.PositiveIntegerField(default=0, help_text='Number of slots owned by the user for group-owned properties.'),
        ),
    ]
