# Generated by Django 5.1.2 on 2024-12-27 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0011_delete_userproperty'),
        ('portfolio', '0010_expenses_user_income_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='group_property',
            field=models.ForeignKey(blank=True, help_text='The group property this user property is associated with.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_properties', to='enterprise.groupproperty'),
        ),
    ]
