# Generated by Django 5.1.2 on 2024-12-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_property_slot_price_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='slot_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Price per slot for group-owned properties.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='slot_price_current',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Price per slot, calculated based on current cost and total slots.', max_digits=10, null=True),
        ),
    ]
