# Generated by Django 5.1.2 on 2024-12-28 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_property_slot_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='group_property',
        ),
    ]
