# Generated by Django 5.1.2 on 2024-12-28 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0015_alter_groupproperty_slot_price_and_more'),
        ('portfolio', '0015_remove_property_group_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='group_property',
            field=models.ForeignKey(blank=True, help_text='The group property this user property is associated with.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_properties', to='enterprise.groupproperty'),
        ),
    ]
