# Generated by Django 5.1.2 on 2024-12-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_property_group_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('NGN', 'Nigerian Naira')], default='NGN', help_text='Currency for the property transactions.', max_length=3),
        ),
        migrations.AddField(
            model_name='income',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('NGN', 'Nigerian Naira')], default='NGN', help_text='Currency for the property transactions.', max_length=3),
        ),
    ]
