# Generated by Django 5.1.2 on 2024-12-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_expenses_currency_income_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=3, unique=True)),
                ('rate_to_usd', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
    ]
