# Generated by Django 5.1.2 on 2024-12-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_currencyrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyrate',
            name='rate_to_usd',
        ),
        migrations.AddField(
            model_name='currencyrate',
            name='rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
