# Generated by Django 5.1.2 on 2025-01-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_alter_expenses_currency_alter_income_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='location',
            new_name='state',
        ),
    ]
