# Generated by Django 5.1.2 on 2025-01-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_rename_location_property_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default=1, help_text='City where the property is located', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='zip_code',
            field=models.CharField(blank=True, help_text='Zip code of the property location', max_length=20, null=True),
        ),
    ]
