# Generated by Django 5.1.2 on 2025-01-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_property_city_property_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='state',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, help_text='City where the property is located', max_length=100, null=True),
        ),
    ]
