# Generated by Django 5.1.2 on 2025-01-21 19:08

import django.db.models.deletion
import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_rename_state_property_location_alter_property_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('land', 'Land'), ('commercial', 'Commercial Property'), ('office', 'Office Space'), ('warehouse', 'Warehouse'), ('shop', 'Shop/Store'), ('duplex', 'Duplex'), ('bungalow', 'Bungalow'), ('terrace', 'Terrace'), ('semi_detached', 'Semi-Detached House'), ('detached', 'Detached House'), ('farm_land', 'Farm Land'), ('industrial', 'Industrial Property'), ('short_let', 'Short Let'), ('studio', 'Studio Apartment')], max_length=50),
        ),
        migrations.CreateModel(
            name='PortfolioPropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=portfolio.models.upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_property_images', to='portfolio.property')),
            ],
        ),
    ]
