# Generated by Django 5.1.2 on 2025-02-05 06:27

import django.db.models.deletion
import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_alter_property_property_type_portfoliopropertyimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPropertyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=portfolio.models.upload_to)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_property_files', to='portfolio.property')),
            ],
        ),
    ]
