# Generated by Django 5.1.2 on 2025-05-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_portfoliopropertyfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyrate',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
