# Generated by Django 5.1.2 on 2025-05-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_currencyrate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyrate',
            name='base',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
