# Generated by Django 5.1.2 on 2025-03-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.URLField(blank=True, help_text="URL of the sender's profile avatar", max_length=500, null=True),
        ),
    ]
