from django.urls import path
from . import views

urlpatterns = [
    path('list-property/', views.upload_property, name='list_property'),
    path('update-property/', views.upload_property, name='update_property'),
    path('fetch-listed-properties/', views.fetch_listed_properties,
         name='fetch-listed-properties'),
    path('fetch-listing/', views.fetch_listed_light_properties,
         name='fetch-listing'),
    path('properties/<int:property_id>/',
         views.fetch_property_by_id, name='fetch_property_by_id'),
    path('fetch-user-listed-properties/', views.fetch_user_listed_properties,
         name='fetch-user-listed-properties'),
    path('fetch-properties-by-email/', views.fetch_properties_by_email,
         name='fetch-properties-by-email'),
    path('search-property/', views.search_properties, name='search-property'),
    path('view-property/<int:pk>/', views.view_property, name='view-property'),
    path('inquiry-on-property/<int:pk>/',
         views.inquire_property, name='inquiry-on-property'),
    path('properties/upload/', views.PropertyWithFilesUploadView.as_view(),
         name='property_with_files_upload'),
    path('delete-property/<int:pk>/',
         views.delete_property, name='delete-property'),
    path('bookmark-property/<int:pk>/',
         views.toggle_bookmark, name='bookmark_property'),
    path('remove-bookmark/<int:bookmark_id>/',
         views.remove_bookmark, name='remove_bookmark'),
    path('user-bookmarks/', views.get_user_bookmarks, name='user_bookmarks'),
    path('upload-image/', views.PropertyImageUploadView.as_view(), name='upload-image'),
    path('upload-file-market/', views.MarketPropertyFileUploadView.as_view(),
         name='upload-file-market'),
    path('property-file/delete/', views.PropertyFileDeleteAPIView.as_view(),
         name='property-file'),
    path('property/<int:property_id>/features/',
         views.create_market_features, name='create_market_features'),
    path('property/coordinates/', views.CoordinateBulkCreateAPIView.as_view(),
         name='coordinate-bulk-create'),
    path('coordinates/delete/', views.CoordinateDeleteAPIView.as_view(),
         name='delete-coordinate'),
    path('delete-file/<int:pk>/', views.delete_market_property_file,
         name='delete_market_property_file'),
]
