# Generated by Django 5.1.2 on 2024-12-20 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='The user who created this entity.', on_delete=django.db.models.deletion.CASCADE, related_name='created_entities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CorporateEntityMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', help_text='The role of the member in the corporate entity.', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('corporate_entity', models.ForeignKey(help_text='The corporate entity this membership belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='enterprise.corporateentity')),
                ('user', models.ForeignKey(help_text='The user who is a member of this corporate entity.', on_delete=django.db.models.deletion.CASCADE, related_name='corporate_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Corporate Entity Member',
                'verbose_name_plural': 'Corporate Entity Members',
                'unique_together': {('corporate_entity', 'user')},
            },
        ),
    ]
