# Generated by Django 5.1.2 on 2024-12-20 10:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateentity',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the corporate group.', unique=True),
        ),
    ]
