# Generated by Django 5.1.2 on 2024-12-21 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_corporateentity_group_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('under_maintenance', 'Under Maintenance')], max_length=20)),
                ('property_type', models.CharField(choices=[('land', 'Land'), ('private', 'Private House'), ('commercial', 'Commercial Property'), ('residential', 'Residential Property')], max_length=50)),
                ('year_bought', models.PositiveIntegerField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('num_units', models.IntegerField(default=1)),
                ('total_slots', models.PositiveIntegerField(default=100, help_text='Total number of slots available for this property.')),
                ('initial_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('virtual_tour_url', models.URLField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('group_owner', models.ForeignKey(help_text='The group that owns this property.', on_delete=django.db.models.deletion.CASCADE, related_name='group_properties', to='enterprise.corporateentity')),
            ],
        ),
        migrations.CreateModel(
            name='GroupIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_received', models.DateField()),
                ('property', models.ForeignKey(help_text='The group property this income is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='enterprise.groupproperty')),
            ],
        ),
        migrations.CreateModel(
            name='GroupExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_incurred', models.DateField()),
                ('property', models.ForeignKey(help_text='The group property this expense is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='enterprise.groupproperty')),
            ],
        ),
        migrations.CreateModel(
            name='GroupSlotAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots_owned', models.PositiveIntegerField(default=1, help_text='Number of slots owned by this user.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(help_text='The group property associated with this allocation.', on_delete=django.db.models.deletion.CASCADE, related_name='slot_allocations', to='enterprise.groupproperty')),
                ('user', models.ForeignKey(help_text='The user owning these slots.', on_delete=django.db.models.deletion.CASCADE, related_name='group_slot_allocations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
