# Generated by Django 5.1.2 on 2024-12-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_groupproperty_groupincome_groupexpenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupproperty',
            name='slot_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
