# Generated by Django 5.1.2 on 2024-12-24 16:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0005_groupslotallocation_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_slots', models.PositiveIntegerField(default=0, help_text='Total slots booked by the user for this project.')),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total payment made by the user for this project.', max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last updated timestamp.')),
                ('project', models.ForeignKey(help_text='The project associated with this booking.', on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to='enterprise.groupproperty')),
                ('user', models.ForeignKey(help_text='The user associated with this booking.', on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
