# Generated by Django 5.1.2 on 2024-12-26 15:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0006_userbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbooking',
            name='project',
        ),
        migrations.AddField(
            model_name='userbooking',
            name='property',
            field=models.ForeignKey(default=1, help_text='The property associated with this booking.', on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to='enterprise.groupproperty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userbooking',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total payment made by the user for this property.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='userbooking',
            name='total_slots',
            field=models.PositiveIntegerField(default=0, help_text='Total slots booked by the user for this property.'),
        ),
    ]
