# Generated by Django 5.1.2 on 2024-12-26 16:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0007_remove_userbooking_project_userbooking_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbooking',
            name='expense_share',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="The user's share of expenses for this property.", max_digits=15),
        ),
        migrations.AddField(
            model_name='userbooking',
            name='income_share',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="The user's share of incomes from this property.", max_digits=15),
        ),
    ]
