# Generated by Django 5.1.2 on 2024-12-26 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0008_userbooking_expense_share_userbooking_income_share'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('property_type', models.CharField(blank=True, choices=[('land', 'Land'), ('private', 'Private House'), ('commercial', 'Commercial Property'), ('residential', 'Residential Property')], max_length=50)),
                ('year_bought', models.PositiveIntegerField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('num_units', models.IntegerField(blank=True, default=1)),
                ('initial_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('slot_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_slots', models.PositiveIntegerField(blank=True, null=True)),
                ('user_slots', models.PositiveIntegerField(default=0)),
                ('virtual_tour_url', models.URLField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('group_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_properties', to='enterprise.groupproperty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
