# Generated by Django 5.1.2 on 2024-12-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0009_userproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupslotallocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='groupslotallocation',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='pending', help_text='The status of the slot allocation.', max_length=20),
        ),
    ]
