# Generated by Django 5.1.2 on 2024-12-27 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0010_groupslotallocation_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProperty',
        ),
    ]
