# Generated by Django 5.1.2 on 2024-12-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0011_delete_userproperty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupproperty',
            options={'verbose_name': 'Group Property', 'verbose_name_plural': 'Group Properties'},
        ),
        migrations.AddField(
            model_name='groupproperty',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('NGN', 'Nigerian Naira')], default='NGN', help_text='Currency for the property transactions.', max_length=3),
        ),
        migrations.AlterField(
            model_name='groupproperty',
            name='slot_price',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Price per slot, calculated based on initial cost and total slots.', max_digits=10),
        ),
    ]
