# Generated by Django 5.1.2 on 2024-12-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0012_alter_groupproperty_options_groupproperty_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupslotallocation',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.DeleteModel(
            name='UserBooking',
        ),
    ]
