# Generated by Django 5.1.2 on 2024-12-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0013_alter_groupslotallocation_total_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupproperty',
            name='slot_price_current',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, help_text='Price per slot, calculated based on current cost and total slots.', max_digits=10),
            preserve_default=False,
        ),
    ]
