# Generated by Django 5.1.2 on 2024-12-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0014_groupproperty_slot_price_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupproperty',
            name='slot_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Price per slot, calculated based on initial cost and total slots.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='groupproperty',
            name='slot_price_current',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Price per slot, calculated based on current cost and total slots.', max_digits=10, null=True),
        ),
    ]
