# Generated by Django 5.1.2 on 2025-01-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0016_groupexpenses_currency_groupincome_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateentitymember',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SUPERADMIN', 'SuperAdmin'), ('MEMBER', 'Member')], default='MEMBER', help_text='The role of the member in the corporate entity.', max_length=10),
        ),
    ]
