# Generated by Django 5.1.2 on 2025-01-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0017_alter_corporateentitymember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupslotallocation',
            name='booking_reference',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
    ]
