# Generated by Django 5.1.2 on 2025-01-20 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0018_groupslotallocation_booking_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupproperty',
            old_name='location',
            new_name='state',
        ),
    ]
