# Generated by Django 5.1.2 on 2025-01-21 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0022_alter_groupproperty_property_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioPropertyImage',
            new_name='GroupPropertyImage',
        ),
    ]
