# Generated by Django 5.1.2 on 2025-02-09 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0023_rename_portfoliopropertyimage_grouppropertyimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(default='MEMBER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('corporate_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.corporateentity')),
            ],
        ),
    ]
