# Generated by Django 5.1.2 on 2025-03-06 08:46

import django.db.models.deletion
import enterprise.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0024_invitationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPropertyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=enterprise.models.upload_to)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_property_files', to='enterprise.groupproperty')),
            ],
        ),
    ]
