# Generated by Django 5.1.2 on 2025-03-07 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0025_grouppropertyfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_coordinates', to='enterprise.groupproperty')),
            ],
        ),
    ]
