# Generated by Django 5.1.2 on 2025-03-14 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0026_groupcoordinate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupproperty',
            name='slot_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per slot, calculated based on initial cost and total slots.', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ReleasedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_slots', models.PositiveIntegerField()),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='released_slots', to='enterprise.corporateentity')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='released_slots', to='enterprise.groupproperty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='released_slots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
